version: "3"
services:
    web:
        build: .
        image: todo_web
        ports:
            - "8000:80"
        depends_on:
            - mongo
    mongo:
        image: "mongo:4.0"
        ports:
        - "27017:27017"